src/SB/Bundle/UserBundle/Entity/Confidentiality.php
<?php

namespace SB\Bundle\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Confidentiality
 *
 * @ORM\Table(name="confidentiality")
 * @ORM\Entity(repositoryClass="SB\Bundle\UserBundle\Repository\ConfidentialityRepository")
 */
class Confidentiality
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var bool
     *
     * @ORM\Column(name="firstname", type="boolean")
     */
    private $firstname;

    /**
     * @var bool
     *
     * @ORM\Column(name="lastname", type="boolean")
     */
    private $lastname;

    /**
     * @var bool
     *
     * @ORM\Column(name="pays", type="boolean")
     */
    private $pays;

    /**
     * @var bool
     *
     * @ORM\Column(name="region", type="boolean")
     */
    private $region;

    /**
     * @var bool
     *
     * @ORM\Column(name="ville", type="boolean")
     */
    private $ville;

    /**
     * @var bool
     *
     * @ORM\Column(name="avatar", type="boolean")
     */
    private $avatar;

    /**
     * @var bool
     *
     * @ORM\Column(name="cover", type="boolean")
     */
    private $cover;

    /**
     * @var bool
     *
     * @ORM\Column(name="activity", type="boolean")
     */
    private $activity;

    public function __construct()
    {
        $this->firstname = false;
        $this->lastname = false;
        $this->pays = false;
        $this->region = false;
        $this->ville = false;
        $this->avatar = false;
        $this->cover = false;
        $this->activity = false;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstname
     *
     * @param boolean $firstname
     *
     * @return Confidentiality
     */
    public function setFirstnameConf($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return bool
     */
    public function getFirstnameConf()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param boolean $lastname
     *
     * @return Confidentiality
     */
    public function setLastnameConf($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return bool
     */
    public function getLastnameConf()
    {
        return $this->lastname;
    }

    /**
     * Set pays
     *
     * @param boolean $pays
     *
     * @return Confidentiality
     */
    public function setPaysConf($pays)
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * Get pays
     *
     * @return bool
     */
    public function getPaysConf()
    {
        return $this->pays;
    }

    /**
     * Set region
     *
     * @param boolean $region
     *
     * @return Confidentiality
     */
    public function setRegionConf($region)
    {
        $this->region = $region;

        return $this;
    }

    /**
     * Get region
     *
     * @return bool
     */
    public function getRegionConf()
    {
        return $this->region;
    }

    /**
     * Set ville
     *
     * @param boolean $ville
     *
     * @return Confidentiality
     */
    public function setVilleConf($ville)
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * Get ville
     *
     * @return bool
     */
    public function getVilleConf()
    {
        return $this->ville;
    }

    /**
     * Set avatar
     *
     * @param boolean $avatar
     *
     * @return Confidentiality
     */
    public function setAvatarConf($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return bool
     */
    public function getAvatarConf()
    {
        return $this->avatar;
    }

    /**
     * Set cover
     *
     * @param boolean $cover
     *
     * @return Confidentiality
     */
    public function setCoverConf($cover)
    {
        $this->cover = $cover;

        return $this;
    }

    /**
     * Get cover
     *
     * @return bool
     */
    public function getCoverConf()
    {
        return $this->cover;
    }

    /**
     * Set activity
     *
     * @param boolean $activity
     *
     * @return Confidentiality
     */
    public function setActivityConf($activity)
    {
        $this->activity = $activity;

        return $this;
    }

    /**
     * Get activity
     *
     * @return bool
     */
    public function getActivityConf()
    {
        return $this->activity;
    }
}

src/SB/Bundle/UserBundle/Controller/ProfilController.php
<?php

namespace SB\Bundle\UserBundle\Controller;

use SB\Bundle\ActivityBundle\Entity\Activity;
use SB\Bundle\UserBundle\Entity\Avatar;
use SB\Bundle\UserBundle\Entity\Cover;
use SB\Bundle\UserBundle\Form\Type\AvatarType;
use SB\Bundle\UserBundle\Form\Type\CoverType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class ProfilController extends Controller
{
    public function profilAction($slugUsername)
    {
        $user = $this->getUser();
        if ($user->getSlug() != $slugUsername) {
            return $this->friendProfilAction($slugUsername);
        }
        $form_add_activity = $this->container->get('sb_activity.activity')->getForm(new Activity(), 'sb_activity_profil_add');
        $em = $this->getDoctrine()->getManager();
        $activityRepository = $em->getRepository('SBActivityBundle:Activity');
        $form_avatar = $this->createForm(AvatarType::class, new Avatar($this->get('kernel')->getRootDir()), array(
            'action' => $this->generateUrl('sb_user_profil_update_profil_avatar')
        ));
        $form_cover = $this->createForm(CoverType::class, new Cover($this->get('kernel')->getRootDir()), array(
            'action' => $this->generateUrl('sb_user_profil_update_profil_cover')
        ));

        return $this->render('SBUserBundle:Profil:profil.html.twig', array(
            'list_activity'         => $activityRepository->fetchAll($user->getId(), array(), 5),
            'number_of_activity'    => $activityRepository->countAll($user->getId(), array()),
            'form_add_activity'     => $form_add_activity->createView(),
            'form_avatar'           => $form_avatar->createView(),
            'form_cover'            => $form_cover->createView(),
            'notifications'         => $user->getNotifications()
        ));
    }

    private function friendProfilAction($slugUsername)
    {
        $em = $this->getDoctrine()->getManager();

        return $this->render('SBUserBundle:Profil:friend_profil.html.twig');
    }

    public function updateProfilAction(Request $request)
    {
        if ($request->isXmlHttpRequest()) {
            $champ = $request->request->get('champ');
            $new_value = $request->request->get('new_value');
            $this->container->get('sb_user.user')->updateProfilInformations($this->getUser(), $champ, $new_value);

            return new JsonResponse(array('result' => true));
        }
        return $this->redirectToRoute('sb_core_homepage');
    }

    public function updateProfilConfidentialityAction(Request $request)
    {
        if ($request->isXmlHttpRequest()) {
            $champ = $request->request->get('champ');
            $new_value = $request->request->get('new_value');
            $this->container->get('sb_user.user')->updateProfilConfidentiality($this->getUser(), $champ, $new_value);

            return new JsonResponse(array('result' => true));
        }
        return $this->redirectToRoute('sb_core_homepage');
    }

    public function updateProfilAvatarAction(Request $request)
    {
        $avatar = new Avatar($this->container->get('kernel')->getRootDir());
        $form_avatar = $this->createForm(AvatarType::class, $avatar);
        $form_avatar->handleRequest($request);
        if ($form_avatar->isSubmitted() && $form_avatar->isValid()) {
            $user = $this->getUser();
            $em = $this->getDoctrine()->getManager();
            $user = $em->getRepository('SBUserBundle:User')->findOneBy(array('id' => $user->getId()));

            if (!is_null($avatar->getFile())) {
                $avatar->upload($user->getUsername());
                $user->setAvatar($avatar);
            }

            $em->persist($user);
            $em->persist($avatar);
            $em->flush();

            return $this->redirectToRoute('sb_user_profil', array('slugUsername' => $user->getSlug()));
        }
        return $this->redirectToRoute('sb_core_homepage');
    }

    public function updateProfilCoverAction(Request $request)
    {
        $cover = new Cover($this->container->get('kernel')->getRootDir());
        $form_cover = $this->createForm(CoverType::class, $cover);
        $form_cover->handleRequest($request);
        if ($form_cover->isSubmitted() && $form_cover->isValid()) {
            $user = $this->getUser();
            $em = $this->getDoctrine()->getManager();
            $user = $em->getRepository('SBUserBundle:User')->findOneBy(array('id' => $user->getId()));

            if (!is_null($cover->getFile())) {
                $cover->upload($user->getUsername());
                $user->setCover($cover);
            }

            $em->persist($user);
            $em->persist($cover);
            $em->flush();

            return $this->redirectToRoute('sb_user_profil', array('slugUsername' => $user->getSlug()));
        }
        return $this->redirectToRoute('sb_core_homepage');
    }
}

src/SB/Bundle/UserBundle/Resources/views/Profil/profil.html.twig
{% extends 'SBCoreBundle::layout.html.twig' %}

{% import 'SBUserBundle:Utils:user.html.twig' as user_macro %}

{% block title %}
    Mon profil -
{% endblock title %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets filter='?uglifycss' filter='cssrewrite'
    'bundles/sbuser/css/profil.css'
    'assets/external/libs/bootstrap-toggle/css/bootstrap-toggle.min.css' %}
    <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}
{% endblock stylesheets %}


{% block js %}
    {% javascripts filter='?uglifyjs2'
        'http://localhost:3000/faye/client.js'
        'assets/external/libs/angular/angular.min.js'
        'assets/external/libs/angular-send-feedback/dist/angular-send-feedback.min.js'
        'assets/external/libs/autogrow-textarea/jquery.autogrowtextarea.min.js'
        'assets/external/libs/remarkable-bootstrap-notify/bootstrap-notify.min.js'
        'assets/external/libs/waypoints/lib/jquery.waypoints.min.js'
        'assets/external/libs/bootstrap-toggle/js/bootstrap-toggle.min.js'
        'assets/app/js/app.js'
        'bundles/sbuser/js/user.js'
        'bundles/sbuser/js/profil.js'
        'bundles/sbactivity/js/activities.js'
        'bundles/sbactivity/js/likes.js'
        'bundles/sbactivity/js/comments.js'
        'bundles/sbactivity/js/activity.js'
        'bundles/sbactivity/js/my-activity.js'
        'assets/app/js/feedback.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <!--<script src="{{ asset('assets/external/libs/jquery-ui/jquery-ui.min.js') }}"></script>-->
    <!--<script src="{{ asset('assets/external/libs/JQ-Image-Drag/script/jquery.imagedrag.min.js') }}"></script>-->
{% endblock js %}

{% block body %}
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <article class="no-padding">
                    <div id="blocks-couverture">
                        {{ user_macro.getCover(app.user.cover, 'myProfil') }}
                        <span>
                            <i class="fa fa-pencil-square fa-3x" aria-hidden="true" data-toggle="modal"
                               data-target="#modalCover"></i>
                        </span>
                    </div>
                    <div id="blocks-profil">
                        {{ user_macro.getAvatar(app.user.avatar, 'myProfil') }}
                    </div>
                    <div id="blocks-nav-profil">
                        <ul>
                            <li><h4 id="zone-profil-name">{{ user_macro.getUserProfilName() }}</h4></li>
                            <li>
                                <a href="#" class="btn btn-infos" id="btnSubmitNewActu">
                                    <i class="fa fa-cogs" aria-hidden="true"></i> Mes paramètres
                                </a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-infos" id="btnSubmitNewActu">
                                    <i class="fa fa-picture-o" aria-hidden="true"></i> Mes images
                                </a>
                            </li>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-3 ml-20 mr-50 mt-20">
                        <div class="row">
                            <div class="col-md-12 activity pb-20 no-pr" id="blocks-user-information">
                                <h4><i class="fa fa-info" aria-hidden="true"></i> Mes informations</h4>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ user_macro.getConfidentiality(app.user.confidentiality.firstnameConf, app.user.firstname, 'Prenom') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ user_macro.getConfidentiality(app.user.confidentiality.lastnameConf, app.user.lastname, 'Nom') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ user_macro.getConfidentiality(app.user.confidentiality.paysConf, app.user.pays, 'Pays') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ user_macro.getConfidentiality(app.user.confidentiality.regionConf, app.user.region, 'Region') }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ user_macro.getConfidentiality(app.user.confidentiality.villeConf, app.user.ville, 'Ville') }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 mt-20">
                        <div class="row">
                            {% set profil = true %}
                            {% include('SBActivityBundle:activity:form_add.html.twig') %}
                        </div>
                        <div id="container-activity" data-total-ativity="{{ number_of_activity }}">
                            {% include('SBActivityBundle:activity:activity.html.twig') %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Cover -->
    <div class="modal fade" id="modalCover" tabindex="-1" role="dialog" aria-labelledby="modalCoverLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalCoverLabel">Modifier ma couverture</h4>
                </div>
                {{ form_start(form_cover) }}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h5 class="text-center">Image de couverture actuelle :</h5>
                                    {{ user_macro.getCover(app.user.cover, 'myProfil', 'inModal') }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    {{ user_macro.getConfidentialityCheckbox('btn-toggle-cover-visibility', app.user.confidentiality.coverConf) }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="col-xs-12">
                            {{ form_widget(form_cover.file) }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary" id="btnChangeCover">Sauvegarder</button>
                </div>
                {{ form_end(form_cover) }}
            </div>
        </div>
    </div>
    <!-- Modal Avatar -->
    <div class="modal fade" id="modalAvatar" tabindex="-1" role="dialog" aria-labelledby="modalAvatarLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalAvatarLabel">Modifier mon avatar</h4>
                </div>
                {{ form_start(form_avatar) }}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h5 class="text-center">Avatar actuel :</h5>
                                    {{ user_macro.getAvatar(app.user.avatar, 'myProfil', 'inModal') }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    {{ user_macro.getConfidentialityCheckbox('btn-toggle-avatar-visibility', app.user.confidentiality.avatarConf) }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="col-xs-12">
                            {{ form_widget(form_avatar.file) }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary" id="btnChangeAvatar">Sauvegarder</button>
                </div>
                {{ form_end(form_avatar) }}
            </div>
        </div>
    </div>
{% endblock body %}